# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: dfb0404
_src_path: https://github.com/qiime2/q2-setup-template.git
module_name: sapienns
plugin_name: q2_sapienns
plugin_scripts: null
project_author_email: greg.caporaso@nau.edu
project_author_name: Greg Caporaso
project_description: null
project_name: q2-sapienns
project_urls_homepage: https://github.com/gregcaporaso/q2-sapienns
project_urls_repository: https://github.com/caporaso-lab/q2-sapienns
